# 服务配置
services:
  # Java 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiztest-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DOCKER_MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/${DB_MONGODB_DATABASE}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
      - mongodb
      - redis
    restart: always
    networks:
      - quiztest-network

  # React 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiztest-frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - frontend_build:/app/dist
    depends_on:
      - backend
    restart: always
    networks:
      - quiztest-network

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: quiztest-mysql
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - quiztest_mysql_data:/var/lib/mysql
      - ./docker/mysql-dump.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
      - ./docker/mysql-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - quiztest-network

  # MongoDB 数据库
  mongodb:
    image: mongo:7.0
    container_name: quiztest-mongodb
    ports:
      - "${DOCKER_MONGODB_PORT}:27017"
    volumes:
      - quiztest_mongodb_data:/data/db
      - ./docker/mongo-dump:/docker-entrypoint-initdb.d/mongo-dump
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    restart: always
    networks:
      - quiztest-network

  # Redis 缓存
  redis:
    image: redis:8.0
    container_name: quiztest-redis
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - quiztest_redis_data:/data
    restart: always
    networks:
      - quiztest-network

  # Nginx 反向代理
  nginx:
    image: nginx:1.21
    container_name: quiztest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - quiztest-network

# 命名卷标
volumes:
  quiztest_mysql_data:
    name: quiztest_mysql_data
  quiztest_mongodb_data:
    name: quiztest_mongodb_data
  quiztest_redis_data:
    name: quiztest_redis_data
  frontend_build:
    name: quiztest_frontend_build

# 网络
networks:
  quiztest-network:
    driver: bridge 