spring:
  datasource:
    url: jdbc:mysql://mysql:3306/quiztest
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://mongodb:27017/quiztest
    redis:
      host: redis
      port: 6379
  jpa:
    show-sql: false

logging:
  level:
    com.quiztest: INFO
    org.springframework: WARN 